### ISSUE TITLE
Delay between opening page and first display of the code

### ISSUE THREAD

**Issue by lukechurch** [devoncarew/dartpad_ui#11]
There's a fairly noticeable delay between the page first loading and the dart code appearing in the LHS window, this gives a perception of slowness.

The delay is noticeable worse on a tablet than a laptop, I suspect it's something to do with the way the editor is being initied?

**Comment by devoncarew** [comment]
We should find a way to measure the time to initial paint, and the time to being editable, and track that on a site like https://www.librato.com/.

**Comment by devoncarew** [comment]
This delay can be minimized once we have a slightly more mature build process, and settle down to using either codemirror or ace.

**Comment by lukechurch** [comment]
sgtm.

**Comment by devoncarew** [comment]
This issue was moved to dart-lang/dartpad_ui#2
