### ISSUE TITLE
Run button should return focus to the text edit area

### ISSUE THREAD

**Issue by lukechurch** [devoncarew/dartpad_ui#12]
I've frequently made a mistake when using the UI, that I edit thing, hit run, and hit backspace which navigates away from the page. It results in a pretty frustrating experience.

I think the easiest way of fixing it have the run button refocus on the text edit area after clicking.

**Comment by devoncarew** [comment]
Sounds good. Perhaps making it not being able to have focus at all - so we never lose it from the text area? But then it wouldn't be tabbable - navigable from the keyboard.

**Comment by lukechurch** [comment]
Not have focus at all sounds good - but I'd be concerned about accessibility impact if we can't tab. Lets check in with the AUX guidelines.

**Comment by devoncarew** [comment]
Done (https://github.com/devoncarew/dartpad_ui/pull/13) - we refocus the text area. The run button is still tab focusable.
