### ISSUE TITLE
The error for using dart:io is unhelpful

### ISSUE THREAD

**Issue by lukechurch** [devoncarew/dartpad_ui#14]
"Error compiling:
[500 Internal Server Error] [error, line 1] Library not found 'dart:io'."

Should be something along the lines of 

"The dart:io library cannot be used in a browser context. Please see _support page_ for common work arounds."

Lets chat about where we put in the fix.

**Comment by devoncarew** [comment]
It now reads:
```
There was an issue when compiling to JavaScript:
[error, line 1] Library not found 'dart:io'.
```
Which is an intermediate step towards the above solution.

**Comment by devoncarew** [comment]
This issue was moved to dart-lang/dartpad_ui#3
