### ISSUE TITLE
italics for keywords doesn't read well

### ISSUE THREAD

**Issue by lukechurch** [devoncarew/dartpad_ui#9]
Eye-tracking studies show the primary benefit of syntax highlighting is allow users to ignore parts of the text quickly, making the keywords mono-space italics makes them harder to skip read and hence harder to ignore.

Recommend remove italics

**Comment by devoncarew** [comment]
Removed (https://github.com/devoncarew/dartpad_ui/pull/13) - we tweak the specific Ace theme that we're using.
